# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dennis\stack\documents\work\LabelingApp\gui\designer_new_subject.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(508, 333)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(140, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setGeometry(QtCore.QRect(20, 50, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.label_color = QtWidgets.QLabel(Dialog)
        self.label_color.setGeometry(QtCore.QRect(20, 80, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_color.setFont(font)
        self.label_color.setObjectName("label_color")
        self.label_size = QtWidgets.QLabel(Dialog)
        self.label_size.setGeometry(QtCore.QRect(20, 110, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_size.setFont(font)
        self.label_size.setObjectName("label_size")
        self.label_extra_info = QtWidgets.QLabel(Dialog)
        self.label_extra_info.setGeometry(QtCore.QRect(20, 140, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_extra_info.setFont(font)
        self.label_extra_info.setObjectName("label_extra_info")
        self.plainTextEdit_extra_info = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_extra_info.setGeometry(QtCore.QRect(100, 140, 381, 141))
        self.plainTextEdit_extra_info.setReadOnly(False)
        self.plainTextEdit_extra_info.setObjectName("plainTextEdit_extra_info")
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_name.setGeometry(QtCore.QRect(100, 50, 241, 20))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_color = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_color.setGeometry(QtCore.QRect(100, 80, 241, 20))
        self.lineEdit_color.setObjectName("lineEdit_color")
        self.lineEdit_size = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_size.setGeometry(QtCore.QRect(100, 110, 241, 20))
        self.lineEdit_size.setObjectName("lineEdit_size")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_warning_duplicate_name = QtWidgets.QLabel(Dialog)
        self.label_warning_duplicate_name.setEnabled(True)
        self.label_warning_duplicate_name.setGeometry(QtCore.QRect(360, 50, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_warning_duplicate_name.setPalette(palette)
        self.label_warning_duplicate_name.setObjectName("label_warning_duplicate_name")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Labeling App"))
        self.label_name.setText(_translate("Dialog", "Name:"))
        self.label_color.setText(_translate("Dialog", "Color:"))
        self.label_size.setText(_translate("Dialog", "Size:"))
        self.label_extra_info.setText(_translate("Dialog", "Extra info:"))
        self.label.setText(_translate("Dialog", "Add a new subject"))
        self.label_warning_duplicate_name.setText(_translate("Dialog", "Name already exists"))
