# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\denni\Documents\LabelingApp\project_new\LabelingApp\gui\designer_camera_settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(448, 491)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 22, 431, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_camera = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_camera.setFont(font)
        self.label_camera.setTextFormat(QtCore.Qt.AutoText)
        self.label_camera.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_camera.setObjectName("label_camera")
        self.verticalLayout_2.addWidget(self.label_camera)
        self.comboBox_camera = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_camera.setObjectName("comboBox_camera")
        self.verticalLayout_2.addWidget(self.comboBox_camera)
        self.label_new_camera = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_new_camera.sizePolicy().hasHeightForWidth())
        self.label_new_camera.setSizePolicy(sizePolicy)
        self.label_new_camera.setObjectName("label_new_camera")
        self.verticalLayout_2.addWidget(self.label_new_camera)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_new_camera = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_new_camera.sizePolicy().hasHeightForWidth())
        self.lineEdit_new_camera.setSizePolicy(sizePolicy)
        self.lineEdit_new_camera.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_new_camera.setObjectName("lineEdit_new_camera")
        self.horizontalLayout_2.addWidget(self.lineEdit_new_camera)
        self.pushButton_new_camera = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_new_camera.sizePolicy().hasHeightForWidth())
        self.pushButton_new_camera.setSizePolicy(sizePolicy)
        self.pushButton_new_camera.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_new_camera.setShortcut("")
        self.pushButton_new_camera.setObjectName("pushButton_new_camera")
        self.horizontalLayout_2.addWidget(self.pushButton_new_camera)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_timezone = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_timezone.setFont(font)
        self.label_timezone.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timezone.setObjectName("label_timezone")
        self.verticalLayout_2.addWidget(self.label_timezone)
        self.lineEdit_timezone = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_timezone.setObjectName("lineEdit_timezone")
        self.verticalLayout_2.addWidget(self.lineEdit_timezone)
        self.listWidget_timezones = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget_timezones.setObjectName("listWidget_timezones")
        self.verticalLayout_2.addWidget(self.listWidget_timezones)
        self.pushButton_save_timezone = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save_timezone.setEnabled(False)
        self.pushButton_save_timezone.setDefault(False)
        self.pushButton_save_timezone.setFlat(False)
        self.pushButton_save_timezone.setObjectName("pushButton_save_timezone")
        self.verticalLayout_2.addWidget(self.pushButton_save_timezone)
        self.pushButton_use_camera = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_use_camera.setObjectName("pushButton_use_camera")
        self.verticalLayout_2.addWidget(self.pushButton_use_camera)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_camera.setText(_translate("Dialog", "Camera"))
        self.label_new_camera.setText(_translate("Dialog", "Add new camera:"))
        self.pushButton_new_camera.setText(_translate("Dialog", "Add"))
        self.label_timezone.setText(_translate("Dialog", "Timezone"))
        self.pushButton_save_timezone.setText(_translate("Dialog", "Save timezone settings"))
        self.pushButton_use_camera.setText(_translate("Dialog", "Use this camera"))
