# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dennis\stack\documents\work\LabelingApp\gui\label_settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(428, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 391, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_label = QtWidgets.QVBoxLayout()
        self.verticalLayout_label.setObjectName("verticalLayout_label")
        self.label_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_label.setFont(font)
        self.label_label.setAlignment(QtCore.Qt.AlignCenter)
        self.label_label.setObjectName("label_label")
        self.verticalLayout_label.addWidget(self.label_label)
        self.comboBox_label = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_label.setObjectName("comboBox_label")
        self.verticalLayout_label.addWidget(self.comboBox_label)
        self.horizontalLayout.addLayout(self.verticalLayout_label)
        self.verticalLayout_color = QtWidgets.QVBoxLayout()
        self.verticalLayout_color.setObjectName("verticalLayout_color")
        self.label_color = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_color.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_color.setFont(font)
        self.label_color.setAlignment(QtCore.Qt.AlignCenter)
        self.label_color.setObjectName("label_color")
        self.verticalLayout_color.addWidget(self.label_color)
        self.comboBox_color = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_color.setObjectName("comboBox_color")
        self.verticalLayout_color.addWidget(self.comboBox_color)
        self.horizontalLayout.addLayout(self.verticalLayout_color)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_new_label = QtWidgets.QHBoxLayout()
        self.horizontalLayout_new_label.setObjectName("horizontalLayout_new_label")
        self.label_new_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_new_label.setObjectName("label_new_label")
        self.horizontalLayout_new_label.addWidget(self.label_new_label)
        self.lineEdit_new_label = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_new_label.setObjectName("lineEdit_new_label")
        self.horizontalLayout_new_label.addWidget(self.lineEdit_new_label)
        self.comboBox_new_label_color = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_new_label_color.setObjectName("comboBox_new_label_color")
        self.horizontalLayout_new_label.addWidget(self.comboBox_new_label_color)
        self.verticalLayout.addLayout(self.horizontalLayout_new_label)
        self.gridLayout_opacity = QtWidgets.QGridLayout()
        self.gridLayout_opacity.setObjectName("gridLayout_opacity")
        self.doubleSpinBox_opacity = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_opacity.setDecimals(0)
        self.doubleSpinBox_opacity.setMinimum(0.0)
        self.doubleSpinBox_opacity.setMaximum(100.0)
        self.doubleSpinBox_opacity.setProperty("value", 50.0)
        self.doubleSpinBox_opacity.setObjectName("doubleSpinBox_opacity")
        self.gridLayout_opacity.addWidget(self.doubleSpinBox_opacity, 0, 1, 1, 1)
        self.label_opacity = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_opacity.setObjectName("label_opacity")
        self.gridLayout_opacity.addWidget(self.label_opacity, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_opacity.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_opacity)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_label.setText(_translate("Dialog", "Labels"))
        self.label_color.setText(_translate("Dialog", "Color"))
        self.pushButton.setText(_translate("Dialog", "Delete label"))
        self.label_new_label.setText(_translate("Dialog", "Add label:"))
        self.label_opacity.setText(_translate("Dialog", "Label color intensity (%):"))
