# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_sensor_model_sensor_id.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not on_accepted this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 346)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_sensorid_explainer = QtWidgets.QLabel(Dialog)
        self.label_sensorid_explainer.setWordWrap(True)
        self.label_sensorid_explainer.setObjectName("label_sensorid_explainer")
        self.gridLayout.addWidget(self.label_sensorid_explainer, 2, 0, 1, 1)
        self.groupBox_sensor_id = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_sensor_id.sizePolicy().hasHeightForWidth())
        self.groupBox_sensor_id.setSizePolicy(sizePolicy)
        self.groupBox_sensor_id.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_sensor_id.setCheckable(True)
        self.groupBox_sensor_id.setChecked(False)
        self.groupBox_sensor_id.setObjectName("groupBox_sensor_id")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_sensor_id)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_row = QtWidgets.QHBoxLayout()
        self.horizontalLayout_row.setObjectName("horizontalLayout_row")
        self.label_row = QtWidgets.QLabel(self.groupBox_sensor_id)
        self.label_row.setObjectName("label_row")
        self.horizontalLayout_row.addWidget(self.label_row)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_row.addItem(spacerItem)
        self.spinBox_row = QtWidgets.QSpinBox(self.groupBox_sensor_id)
        self.spinBox_row.setMinimum(1)
        self.spinBox_row.setObjectName("spinBox_row")
        self.horizontalLayout_row.addWidget(self.spinBox_row)
        self.verticalLayout_2.addLayout(self.horizontalLayout_row)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_column = QtWidgets.QHBoxLayout()
        self.horizontalLayout_column.setObjectName("horizontalLayout_column")
        self.checkBox_column = QtWidgets.QCheckBox(self.groupBox_sensor_id)
        self.checkBox_column.setText("")
        self.checkBox_column.setObjectName("checkBox_column")
        self.horizontalLayout_column.addWidget(self.checkBox_column)
        self.label_column = QtWidgets.QLabel(self.groupBox_sensor_id)
        self.label_column.setObjectName("label_column")
        self.horizontalLayout_column.addWidget(self.label_column)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_column.addItem(spacerItem2)
        self.spinBox_column = QtWidgets.QSpinBox(self.groupBox_sensor_id)
        self.spinBox_column.setMinimum(1)
        self.spinBox_column.setObjectName("spinBox_column")
        self.horizontalLayout_column.addWidget(self.spinBox_column)
        self.verticalLayout_2.addLayout(self.horizontalLayout_column)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_regex = QtWidgets.QHBoxLayout()
        self.horizontalLayout_regex.setObjectName("horizontalLayout_regex")
        self.checkBox_regex = QtWidgets.QCheckBox(self.groupBox_sensor_id)
        self.checkBox_regex.setText("")
        self.checkBox_regex.setObjectName("checkBox_regex")
        self.horizontalLayout_regex.addWidget(self.checkBox_regex)
        self.label_regex = QtWidgets.QLabel(self.groupBox_sensor_id)
        self.label_regex.setObjectName("label_regex")
        self.horizontalLayout_regex.addWidget(self.label_regex)
        self.lineEdit_regex = QtWidgets.QLineEdit(self.groupBox_sensor_id)
        self.lineEdit_regex.setObjectName("lineEdit_regex")
        self.horizontalLayout_regex.addWidget(self.lineEdit_regex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_regex)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_2)
        self.gridLayout.addWidget(self.groupBox_sensor_id, 3, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_previous = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_previous.sizePolicy().hasHeightForWidth())
        self.pushButton_previous.setSizePolicy(sizePolicy)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.horizontalLayout_3.addWidget(self.pushButton_previous)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_test = QtWidgets.QPushButton(Dialog)
        self.pushButton_test.setObjectName("pushButton_test")
        self.horizontalLayout_3.addWidget(self.pushButton_test)
        self.pushButton_next = QtWidgets.QPushButton(Dialog)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_3.addWidget(self.pushButton_next)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add sensor model"))
        self.label_sensorid_explainer.setText(_translate("Dialog", "Most sensordata files print the ID of the sensor as metadata in the headers of each file. The labeling app can parse the ID to automatically recognize the sensor and link the data to a subject."))
        self.groupBox_sensor_id.setTitle(_translate("Dialog", "Sensordata files contain sensor ID or description"))
        self.label_row.setText(_translate("Dialog", "Row"))
        self.label_column.setText(_translate("Dialog", "Column"))
        self.label_regex.setText(_translate("Dialog", "Regex"))
        self.label_title.setText(_translate("Dialog", "Sensor ID"))
        self.pushButton_previous.setText(_translate("Dialog", "Previous"))
        self.pushButton_test.setText(_translate("Dialog", "Test"))
        self.pushButton_next.setText(_translate("Dialog", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
