# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\denni\Documents\LabelingApp\project_new\LabelingApp\gui\designer\new_sensor_model_final_new.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 430)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_2.addWidget(self.pushButton_save, 2, 2, 1, 1)
        self.label_title = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 1, 1, 2)
        self.pushButton_previous = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_previous.sizePolicy().hasHeightForWidth())
        self.pushButton_previous.setSizePolicy(sizePolicy)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.gridLayout_2.addWidget(self.pushButton_previous, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_comment_style_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_comment_style_label.setFont(font)
        self.label_comment_style_label.setObjectName("label_comment_style_label")
        self.gridLayout.addWidget(self.label_comment_style_label, 4, 2, 1, 1)
        self.label_name_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_name_label.setFont(font)
        self.label_name_label.setObjectName("label_name_label")
        self.gridLayout.addWidget(self.label_name_label, 0, 0, 1, 1)
        self.label_headers_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_headers_label.setFont(font)
        self.label_headers_label.setObjectName("label_headers_label")
        self.gridLayout.addWidget(self.label_headers_label, 2, 2, 1, 1)
        self.label_time_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_time_label.setFont(font)
        self.label_time_label.setObjectName("label_time_label")
        self.gridLayout.addWidget(self.label_time_label, 4, 0, 1, 1)
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setText("")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 1, 0, 1, 1)
        self.label_id_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_label.setFont(font)
        self.label_id_label.setObjectName("label_id_label")
        self.gridLayout.addWidget(self.label_id_label, 0, 2, 1, 1)
        self.label_date_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_date_label.setFont(font)
        self.label_date_label.setObjectName("label_date_label")
        self.gridLayout.addWidget(self.label_date_label, 2, 0, 1, 1)
        self.label_comment_style = QtWidgets.QLabel(Dialog)
        self.label_comment_style.setText("")
        self.label_comment_style.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_comment_style.setObjectName("label_comment_style")
        self.gridLayout.addWidget(self.label_comment_style, 5, 2, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_headers_row = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_headers_row.setFont(font)
        self.label_headers_row.setText("")
        self.label_headers_row.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_headers_row.setObjectName("label_headers_row")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_headers_row)
        self.label_headers_row_label = QtWidgets.QLabel(Dialog)
        self.label_headers_row_label.setObjectName("label_headers_row_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_headers_row_label)
        self.gridLayout.addLayout(self.formLayout_3, 3, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_time_format_label = QtWidgets.QLabel(Dialog)
        self.label_time_format_label.setObjectName("label_time_format_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_time_format_label)
        self.label_time_format = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_time_format.setFont(font)
        self.label_time_format.setText("")
        self.label_time_format.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time_format.setObjectName("label_time_format")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_time_format)
        self.label_time_row_label = QtWidgets.QLabel(Dialog)
        self.label_time_row_label.setObjectName("label_time_row_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_time_row_label)
        self.label_time_row = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_time_row.setFont(font)
        self.label_time_row.setText("")
        self.label_time_row.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time_row.setObjectName("label_time_row")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_time_row)
        self.label_time_column_label = QtWidgets.QLabel(Dialog)
        self.label_time_column_label.setObjectName("label_time_column_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_time_column_label)
        self.label_time_column = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_time_column.setFont(font)
        self.label_time_column.setText("")
        self.label_time_column.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time_column.setObjectName("label_time_column")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_time_column)
        self.label_time_regex_label = QtWidgets.QLabel(Dialog)
        self.label_time_regex_label.setObjectName("label_time_regex_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_time_regex_label)
        self.label_time_regex = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_time_regex.setFont(font)
        self.label_time_regex.setText("")
        self.label_time_regex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time_regex.setObjectName("label_time_regex")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_time_regex)
        self.gridLayout.addLayout(self.formLayout, 5, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_id_row_label = QtWidgets.QLabel(Dialog)
        self.label_id_row_label.setObjectName("label_id_row_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_id_row_label)
        self.label_id_row = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_row.setFont(font)
        self.label_id_row.setText("")
        self.label_id_row.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id_row.setObjectName("label_id_row")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_id_row)
        self.label_id_column_label = QtWidgets.QLabel(Dialog)
        self.label_id_column_label.setObjectName("label_id_column_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_id_column_label)
        self.label_id_column = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_column.setFont(font)
        self.label_id_column.setText("")
        self.label_id_column.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id_column.setObjectName("label_id_column")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_id_column)
        self.label_id_regex_label = QtWidgets.QLabel(Dialog)
        self.label_id_regex_label.setObjectName("label_id_regex_label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_id_regex_label)
        self.label_id_regex = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_regex.setFont(font)
        self.label_id_regex.setText("")
        self.label_id_regex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id_regex.setObjectName("label_id_regex")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_id_regex)
        self.gridLayout.addLayout(self.formLayout_4, 1, 2, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_date_format_label = QtWidgets.QLabel(Dialog)
        self.label_date_format_label.setObjectName("label_date_format_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_date_format_label)
        self.label_date_format = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_date_format.setFont(font)
        self.label_date_format.setText("")
        self.label_date_format.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date_format.setObjectName("label_date_format")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_date_format)
        self.label_date_row_label = QtWidgets.QLabel(Dialog)
        self.label_date_row_label.setObjectName("label_date_row_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_date_row_label)
        self.label_date_row = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_date_row.setFont(font)
        self.label_date_row.setText("")
        self.label_date_row.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date_row.setObjectName("label_date_row")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_date_row)
        self.label_date_column_label = QtWidgets.QLabel(Dialog)
        self.label_date_column_label.setObjectName("label_date_column_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_date_column_label)
        self.label_date_column = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_date_column.setFont(font)
        self.label_date_column.setText("")
        self.label_date_column.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date_column.setObjectName("label_date_column")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_date_column)
        self.label_date_regex_label = QtWidgets.QLabel(Dialog)
        self.label_date_regex_label.setObjectName("label_date_regex_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_date_regex_label)
        self.label_date_regex = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_date_regex.setFont(font)
        self.label_date_regex.setText("")
        self.label_date_regex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date_regex.setObjectName("label_date_regex")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_date_regex)
        self.gridLayout.addLayout(self.formLayout_2, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add sensor model"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
        self.label_title.setText(_translate("Dialog", "New sensor model"))
        self.pushButton_previous.setText(_translate("Dialog", "Previous"))
        self.label_comment_style_label.setText(_translate("Dialog", "Comment style"))
        self.label_name_label.setText(_translate("Dialog", "Name"))
        self.label_headers_label.setText(_translate("Dialog", "Headers"))
        self.label_time_label.setText(_translate("Dialog", "Time"))
        self.label_id_label.setText(_translate("Dialog", "Sensor ID"))
        self.label_date_label.setText(_translate("Dialog", "Date"))
        self.label_headers_row_label.setText(_translate("Dialog", "Row"))
        self.label_time_format_label.setText(_translate("Dialog", "Format"))
        self.label_time_row_label.setText(_translate("Dialog", "Row"))
        self.label_time_column_label.setText(_translate("Dialog", "Column"))
        self.label_time_regex_label.setText(_translate("Dialog", "Regex"))
        self.label_id_row_label.setText(_translate("Dialog", "Row"))
        self.label_id_column_label.setText(_translate("Dialog", "Column"))
        self.label_id_regex_label.setText(_translate("Dialog", "Regex"))
        self.label_date_format_label.setText(_translate("Dialog", "Format"))
        self.label_date_row_label.setText(_translate("Dialog", "Row"))
        self.label_date_column_label.setText(_translate("Dialog", "Column"))
        self.label_date_regex_label.setText(_translate("Dialog", "Regex"))
