# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\denni\Documents\LabelingApp\project_new\LabelingApp\gui\designer\new_sensor_model_final.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 350)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setText("")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 2, 0, 1, 2)
        self.label_title = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 1, 1, 3)
        self.label_headers_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_headers_label.setFont(font)
        self.label_headers_label.setObjectName("label_headers_label")
        self.gridLayout.addWidget(self.label_headers_label, 4, 3, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 6, 4, 1, 1)
        self.label_id_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_label.setFont(font)
        self.label_id_label.setObjectName("label_id_label")
        self.gridLayout.addWidget(self.label_id_label, 1, 3, 1, 1)
        self.label_datetime_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_datetime_label.setFont(font)
        self.label_datetime_label.setObjectName("label_datetime_label")
        self.gridLayout.addWidget(self.label_datetime_label, 3, 0, 1, 1)
        self.label_name_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_name_label.setFont(font)
        self.label_name_label.setObjectName("label_name_label")
        self.gridLayout.addWidget(self.label_name_label, 1, 0, 1, 2)
        self.pushButton_previous = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_previous.sizePolicy().hasHeightForWidth())
        self.pushButton_previous.setSizePolicy(sizePolicy)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.gridLayout.addWidget(self.pushButton_previous, 6, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_id_row_label = QtWidgets.QLabel(Dialog)
        self.label_id_row_label.setObjectName("label_id_row_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_id_row_label)
        self.label_id_row = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_row.setFont(font)
        self.label_id_row.setText("")
        self.label_id_row.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id_row.setObjectName("label_id_row")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_id_row)
        self.label_id_column_label = QtWidgets.QLabel(Dialog)
        self.label_id_column_label.setObjectName("label_id_column_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_id_column_label)
        self.label_id_column = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_column.setFont(font)
        self.label_id_column.setText("")
        self.label_id_column.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id_column.setObjectName("label_id_column")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_id_column)
        self.label_id_regex_label = QtWidgets.QLabel(Dialog)
        self.label_id_regex_label.setObjectName("label_id_regex_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_id_regex_label)
        self.label_id_regex = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id_regex.setFont(font)
        self.label_id_regex.setText("")
        self.label_id_regex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_id_regex.setObjectName("label_id_regex")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_id_regex)
        self.gridLayout.addLayout(self.formLayout_2, 2, 3, 2, 2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_headers_row_label = QtWidgets.QLabel(Dialog)
        self.label_headers_row_label.setObjectName("label_headers_row_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_headers_row_label)
        self.label_headers_row = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_headers_row.setFont(font)
        self.label_headers_row.setText("")
        self.label_headers_row.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_headers_row.setObjectName("label_headers_row")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_headers_row)
        self.gridLayout.addLayout(self.formLayout_3, 5, 3, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_datetime_format_label = QtWidgets.QLabel(Dialog)
        self.label_datetime_format_label.setObjectName("label_datetime_format_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_datetime_format_label)
        self.label_datetime_format = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_datetime_format.setFont(font)
        self.label_datetime_format.setText("")
        self.label_datetime_format.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_datetime_format.setObjectName("label_datetime_format")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_datetime_format)
        self.label_datetime_row_label = QtWidgets.QLabel(Dialog)
        self.label_datetime_row_label.setObjectName("label_datetime_row_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_datetime_row_label)
        self.label_datetime_row = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_datetime_row.setFont(font)
        self.label_datetime_row.setText("")
        self.label_datetime_row.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_datetime_row.setObjectName("label_datetime_row")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_datetime_row)
        self.label_datetime_column_label = QtWidgets.QLabel(Dialog)
        self.label_datetime_column_label.setObjectName("label_datetime_column_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_datetime_column_label)
        self.label_datetime_column = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_datetime_column.setFont(font)
        self.label_datetime_column.setText("")
        self.label_datetime_column.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_datetime_column.setObjectName("label_datetime_column")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_datetime_column)
        self.label_datetime_regex_label = QtWidgets.QLabel(Dialog)
        self.label_datetime_regex_label.setObjectName("label_datetime_regex_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_datetime_regex_label)
        self.label_datetime_regex = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_datetime_regex.setFont(font)
        self.label_datetime_regex.setText("")
        self.label_datetime_regex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_datetime_regex.setObjectName("label_datetime_regex")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_datetime_regex)
        self.gridLayout.addLayout(self.formLayout, 4, 0, 2, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add sensor model"))
        self.label_title.setText(_translate("Dialog", "New sensor model"))
        self.label_headers_label.setText(_translate("Dialog", "Headers"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
        self.label_id_label.setText(_translate("Dialog", "Sensor ID"))
        self.label_datetime_label.setText(_translate("Dialog", "Datetime"))
        self.label_name_label.setText(_translate("Dialog", "Name"))
        self.pushButton_previous.setText(_translate("Dialog", "Previous"))
        self.label_id_row_label.setText(_translate("Dialog", "Row"))
        self.label_id_column_label.setText(_translate("Dialog", "Column"))
        self.label_id_regex_label.setText(_translate("Dialog", "Regex"))
        self.label_headers_row_label.setText(_translate("Dialog", "Row"))
        self.label_datetime_format_label.setText(_translate("Dialog", "Format"))
        self.label_datetime_row_label.setText(_translate("Dialog", "Row"))
        self.label_datetime_column_label.setText(_translate("Dialog", "Column"))
        self.label_datetime_regex_label.setText(_translate("Dialog", "Regex"))
