# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\gui\designer\new_sensor_model_date.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 350)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.pushButton_previous = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_previous.sizePolicy().hasHeightForWidth())
        self.pushButton_previous.setSizePolicy(sizePolicy)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.gridLayout_2.addWidget(self.pushButton_previous, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_date_row = QtWidgets.QLabel(Dialog)
        self.label_date_row.setObjectName("label_date_row")
        self.gridLayout.addWidget(self.label_date_row, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.spinBox_time_row = QtWidgets.QSpinBox(Dialog)
        self.spinBox_time_row.setObjectName("spinBox_time_row")
        self.horizontalLayout_2.addWidget(self.spinBox_time_row)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 7, 1, 1, 1)
        self.label_time_row = QtWidgets.QLabel(Dialog)
        self.label_time_row.setObjectName("label_time_row")
        self.gridLayout.addWidget(self.label_time_row, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.spinBox_date_row = QtWidgets.QSpinBox(Dialog)
        self.spinBox_date_row.setObjectName("spinBox_date_row")
        self.horizontalLayout.addWidget(self.spinBox_date_row)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.label_test_date = QtWidgets.QLabel(Dialog)
        self.label_test_date.setText("")
        self.label_test_date.setObjectName("label_test_date")
        self.gridLayout.addWidget(self.label_test_date, 3, 1, 1, 1)
        self.label_test_time = QtWidgets.QLabel(Dialog)
        self.label_test_time.setText("")
        self.label_test_time.setObjectName("label_test_time")
        self.gridLayout.addWidget(self.label_test_time, 6, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 4)
        self.pushButton_next = QtWidgets.QPushButton(Dialog)
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout_2.addWidget(self.pushButton_next, 2, 3, 1, 1)
        self.pushButton_test = QtWidgets.QPushButton(Dialog)
        self.pushButton_test.setObjectName("pushButton_test")
        self.gridLayout_2.addWidget(self.pushButton_test, 2, 2, 1, 1)
        self.label_title = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add sensor model"))
        self.pushButton_previous.setText(_translate("Dialog", "Previous"))
        self.label_date_row.setText(_translate("Dialog", "Date row"))
        self.label_time_row.setText(_translate("Dialog", "Time row"))
        self.pushButton_next.setText(_translate("Dialog", "Next"))
        self.pushButton_test.setText(_translate("Dialog", "Test"))
        self.label_title.setText(_translate("Dialog", "Date/time"))
