# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not on_accepted this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(694, 823)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(694, 823))
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(500, 800))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_select_subjects_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_subjects_2.setFont(font)
        self.label_select_subjects_2.setObjectName("label_select_subjects_2")
        self.gridLayout.addWidget(self.label_select_subjects_2, 3, 0, 1, 1)
        self.listWidget_subjects = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_subjects.sizePolicy().hasHeightForWidth())
        self.listWidget_subjects.setSizePolicy(sizePolicy)
        self.listWidget_subjects.setMinimumSize(QtCore.QSize(0, 50))
        self.listWidget_subjects.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget_subjects.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget_subjects.setObjectName("listWidget_subjects")
        self.gridLayout.addWidget(self.listWidget_subjects, 1, 0, 1, 1)
        self.pushButton_plot_data = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_plot_data.sizePolicy().hasHeightForWidth())
        self.pushButton_plot_data.setSizePolicy(sizePolicy)
        self.pushButton_plot_data.setObjectName("pushButton_plot_data")
        self.gridLayout.addWidget(self.pushButton_plot_data, 3, 1, 1, 1, QtCore.Qt.AlignRight)
        self.listWidget_activities = QtWidgets.QListWidget(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_activities.sizePolicy().hasHeightForWidth())
        self.listWidget_activities.setSizePolicy(sizePolicy)
        self.listWidget_activities.setMinimumSize(QtCore.QSize(0, 10))
        self.listWidget_activities.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget_activities.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget_activities.setObjectName("listWidget_activities")
        self.gridLayout.addWidget(self.listWidget_activities, 4, 0, 1, 1)
        self.groupBox_select_timeperiod = QtWidgets.QGroupBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_select_timeperiod.sizePolicy().hasHeightForWidth())
        self.groupBox_select_timeperiod.setSizePolicy(sizePolicy)
        self.groupBox_select_timeperiod.setMinimumSize(QtCore.QSize(50, 50))
        self.groupBox_select_timeperiod.setCheckable(True)
        self.groupBox_select_timeperiod.setChecked(False)
        self.groupBox_select_timeperiod.setObjectName("groupBox_select_timeperiod")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_select_timeperiod)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 182, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_start = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_2.addWidget(self.label_start)
        self.dateEdit_start = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_start.setObjectName("dateEdit_start")
        self.horizontalLayout_2.addWidget(self.dateEdit_start)
        self.timeEdit_start = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.timeEdit_start.setObjectName("timeEdit_start")
        self.horizontalLayout_2.addWidget(self.timeEdit_start)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_end = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_3.addWidget(self.label_end)
        self.dateEdit_end = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_end.setObjectName("dateEdit_end")
        self.horizontalLayout_3.addWidget(self.dateEdit_end)
        self.timeEdit_end = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.timeEdit_end.setObjectName("timeEdit_end")
        self.horizontalLayout_3.addWidget(self.timeEdit_end)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.groupBox_select_timeperiod, 1, 1, 1, 1)
        self.label_select_subjects_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_subjects_3.setFont(font)
        self.label_select_subjects_3.setObjectName("label_select_subjects_3")
        self.gridLayout.addWidget(self.label_select_subjects_3, 0, 1, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_info_text = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info_text.sizePolicy().hasHeightForWidth())
        self.label_info_text.setSizePolicy(sizePolicy)
        self.label_info_text.setMinimumSize(QtCore.QSize(200, 0))
        self.label_info_text.setWordWrap(True)
        self.label_info_text.setObjectName("label_info_text")
        self.verticalLayout.addWidget(self.label_info_text)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_function = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_function.setObjectName("label_function")
        self.horizontalLayout_4.addWidget(self.label_function)
        self.comboBox_functions = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_functions.setObjectName("comboBox_functions")
        self.horizontalLayout_4.addWidget(self.comboBox_functions)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_y_plot_height = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_y_plot_height.setObjectName("label_y_plot_height")
        self.horizontalLayout.addWidget(self.label_y_plot_height)
        self.doubleSpinBox_plot_height = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.doubleSpinBox_plot_height.setSuffix("")
        self.doubleSpinBox_plot_height.setMinimum(0.01)
        self.doubleSpinBox_plot_height.setMaximum(1000.0)
        self.doubleSpinBox_plot_height.setSingleStep(0.1)
        self.doubleSpinBox_plot_height.setProperty("value", 1.0)
        self.doubleSpinBox_plot_height.setObjectName("doubleSpinBox_plot_height")
        self.horizontalLayout.addWidget(self.doubleSpinBox_plot_height)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_plot_width_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_plot_width_2.setObjectName("horizontalLayout_plot_width_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_plot_width_2.addItem(spacerItem3)
        self.label_plot_width = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_plot_width.setObjectName("label_plot_width")
        self.horizontalLayout_plot_width_2.addWidget(self.label_plot_width)
        self.doubleSpinBox_plot_width = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.doubleSpinBox_plot_width.setMinimumSize(QtCore.QSize(70, 0))
        self.doubleSpinBox_plot_width.setProperty("value", 50.0)
        self.doubleSpinBox_plot_width.setObjectName("doubleSpinBox_plot_width")
        self.horizontalLayout_plot_width_2.addWidget(self.doubleSpinBox_plot_width)
        self.verticalLayout.addLayout(self.horizontalLayout_plot_width_2)
        self.gridLayout.addLayout(self.verticalLayout, 4, 1, 1, 2)
        self.label_select_subjects = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_select_subjects.setFont(font)
        self.label_select_subjects.setObjectName("label_select_subjects")
        self.gridLayout.addWidget(self.label_select_subjects, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalSlider_time = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        self.horizontalSlider_time.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_time.setObjectName("horizontalSlider_time")
        self.verticalLayout_2.addWidget(self.horizontalSlider_time)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_plot = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_plot.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_plot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_plot.setObjectName("verticalLayout_plot")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_select_subjects_2.setText(_translate("Dialog", "Select label"))
        self.pushButton_plot_data.setText(_translate("Dialog", "Plot data"))
        self.groupBox_select_timeperiod.setTitle(_translate("Dialog", "Select time period (deselect to select all data)"))
        self.label_start.setText(_translate("Dialog", "Start:"))
        self.label_end.setText(_translate("Dialog", "End:"))
        self.label_select_subjects_3.setText(_translate("Dialog", "Select time period"))
        self.label_info_text.setText(_translate("Dialog", "Please select subject and label"))
        self.label_function.setText(_translate("Dialog", "Function"))
        self.label_y_plot_height.setText(_translate("Dialog", "Plot height factor"))
        self.label_plot_width.setText(_translate("Dialog", "Plot width (s)"))
        self.label_select_subjects.setText(_translate("Dialog", "Select subject"))
        self.label.setText(_translate("Dialog", "Use slider or left and right arrow keys to scroll through data. Note that all the labeled segments are concattenated. To find out the date and time of the segment, click on the data segment with left mouse button."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
